selmag:
  service:
    catalogue:
      uri: lb://selmag-catalogue-service
    feedback:
      uri: lb://selmag-feedback-service
spring:
  boot:
    admin:
      client:
        enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.109.247:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-secret: MbROevnUr8jmr6OQqH0TSvtyuX1ZUSPc
            authorization-grant-type: authorization_code
            scope:
              - openid
              - view_catalogue
          metrics:
            provider: keycloak
            client-id: customer-app
            client-secret: MbROevnUr8jmr6OQqH0TSvtyuX1ZUSPc
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: customer-app
            client-secret: MbROevnUr8jmr6OQqH0TSvtyuX1ZUSPc
            authorization-grant-type: client_credentials
            scope:
              - discovery
      resourceserver:
        jwt:
          issuer-uri: http://192.168.109.247:8082/realms/selmag
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  jmx:
    metrics:
      export:
        enabled: true
  zipkin:
    tracing:
      endpoint: http://192.168.109.247:9411
  tracing:
    sampling:
      probability: 1.0  
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true   