spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8082/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://127.0.0.1:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: YhTLN4vdqwbfg1gpmAIOYxV2PaVuxPsw
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
              - microprofile-jwt 
            client-id: admin-service
            client-secret: YhTLN4vdqwbfg1gpmAIOYxV2PaVuxPsw
          discovery:
            provider: keycloak
            client-id: admin-service
            client-secret: YhTLN4vdqwbfg1gpmAIOYxV2PaVuxPsw
            authorization-grant-type: client_credentials
            scope:
              - discovery
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
eureka:
  instance:
    hostname: 127.0.0.1
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    registryFetchIntervalSeconds: 1
    register-with-eureka: false