spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.109.247:8082/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.109.247:8082/realms/selmag
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: YhTLN4vdqwbfg1gpmAIOYxV2PaVuxPsw
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
              - microprofile-jwt 
            client-id: admin-service
            client-secret: YhTLN4vdqwbfg1gpmAIOYxV2PaVuxPsw
          discovery:
            provider: keycloak
            client-id: admin-service
            client-secret: YhTLN4vdqwbfg1gpmAIOYxV2PaVuxPsw
            authorization-grant-type: client_credentials
            scope:
              - discovery
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
  instance:
    prefer-ip-address: true   