loki:
     url: ${LOKI:http://192.168.109.247:3100}
spring:
  boot:
    admin:
      client:
        enabled: false    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.109.247:8082/realms/selmag
      client:
        registration:
          keycloak:
            client-id: catalogue-service
            client-secret: HbKzQtkD9OhpMdDji2vKBBTiZap9t0X9
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: catalogue-service
            client-secret: HbKzQtkD9OhpMdDji2vKBBTiZap9t0X9
            authorization-grant-type: client_credentials
            scope:
              - discovery
        provider:
          keycloak: 
            issuer-uri: http://192.168.109.247:8082/realms/selmag
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    username: catalogue
    password: catalogue
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
logging:
  level:
    sql: info
springdoc:
  swagger-ui:
      oauth: 
        client-id: catalogue-service-swagger-ui
        use-pkce-with-authorization-code-grant: true
keycloak:
  uri: http://localhost:8082
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://192.168.109.247:9411
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true   